### ISSUE TITLE
 Issue 6 for Milestone 3: Training the Model (Lab 5-8)

### ISSUE THREAD

**Issue by Rtchie** [Rtchie/BIProject#7]
- [x] Data splitting
- [x] Bootstrapping
- [x] Cross validation (repeated)
- [x] Model training for  classification
- [x] Model performance comparison using resamples (for classification)

**Comment by Rtchie** [comment]
closed because of completion
